### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by sergiojimcos**
Errors 1 and 2 solved

### CODE REVIEW

**Comment by IsmaelCaballero** [comment]
I obtain error when running site:site … does it work to you?

**Comment by sergiojimcos** [comment]
Yes, it works. Which project have you clone?. Are you using jdk 1.8?

**Comment by IsmaelCaballero** [comment]
Now I got it! Thank you

**Comment by sergiojimcos** [comment]
Ok, if you have any advise or any point that we have to check more, please tell us

**Pull request merged**
